"""Deterministic TEST_FIXTURE generator for the Phase 1.8 report-agent inputs.

The Phase 1.8 report tests originally consumed real, gitignored acceptance artifacts from a
developer's private ``artifacts/`` directory (the Phase 1.7-B offline verifier results and the Phase
1.7-D live-recon acceptance + delegation queue). Those artifacts are production evidence — the 1.7-D
set in particular is *live-provider* evidence — so they are neither committed nor safe to treat as a
portable test fixture.

This module regenerates, deterministically and offline, a **synthetic** evidence set with the exact
*structure and cross-references* the report builder validates, so the report contract is exercised
in any fresh checkout without a private artifact directory. Everything here is unmistakably a
``TEST_FIXTURE``:

* the destination directory carries a ``TEST_FIXTURE`` marker file,
* ``acceptance.json`` carries a ``"_fixture": "TEST_FIXTURE"`` field and a fixture phase label,
* the values are fixed constants, never a captured provider transcript.

The verifier records reuse the real *synthetic* scenario ids (``shop-promotion-preview-v1`` /
``shop-catalog-query-v1``) because the report's ground-truth severity trace keys off them; those ids
and the digest/queue-address identifiers are structural, not live-provider content.

The generated bytes are checked in under ``tests/fixtures/phase_1_8_report/`` and
``tests/test_portable_fixtures.py`` asserts this generator reproduces them byte-for-byte, so the
byte-identity contract compares a deterministic generator result rather than a private artifact.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from dataclasses import dataclass
from pathlib import Path

FIXTURE_DIRNAME = "phase_1_8_report"
FIXTURE_MARKER = "TEST_FIXTURE"
# The checked-in location, relative to the repository root. Recorded verbatim in acceptance.json so
# the generated bytes are stable no matter where the generator is run, and so the report builder's
# queue-identity cross-check (`repo_root / artifact_db_path == delegation_queue_path`) resolves to
# the committed fixture when the report tests pass the real repo root.
ARTIFACT_DB_PATH = f"tests/fixtures/{FIXTURE_DIRNAME}/delegation_queue.sqlite3"

# Structural identifiers the report tests pin. These are identifiers/digests, not provider output.
DELEGATION_ID = "delg-bb6dc915960a7d7f"
QUEUE_ADDRESS = f"agentqueue://INJECTION_AGENT/{DELEGATION_ID}"
DELEGATION_EVIDENCE_SHA256 = (
    "7526e1a1894b7096a4a80c0e76845ee4d45b4351b66832fa10d3921907a2b773"
)
ENQUEUED_AT = "2026-09-23T15:37:55.556635Z"

# The eight deterministic synthetic verifier records the offline report transports. Reproduced as
# fixed constants (not read from any private artifact).
_VERIFIER_RECORDS: list[dict[str, object]] = [
    {
        "evidence_sha256": "bde9de637a7738a895db532da63010fafa262f42f9c995c2c92724b378c38e7f",
        "facts": {"candidate_tests": 2, "no_mutation": True, "observed_routes": 8, "warnings": 0},
        "false_positive": False,
        "gate": "recon",
        "mode": "vulnerable",
        "outcome": "PASS",
        "scenario_id": "shop-promotion-preview-v1",
        "verifier_status": None,
    },
    {
        "evidence_sha256": "bde9de637a7738a895db532da63010fafa262f42f9c995c2c92724b378c38e7f",
        "facts": {"candidate_tests": 2, "no_mutation": True, "observed_routes": 8, "warnings": 0},
        "false_positive": False,
        "gate": "recon",
        "mode": "patched",
        "outcome": "PASS",
        "scenario_id": "shop-promotion-preview-v1",
        "verifier_status": None,
    },
    {
        "evidence_sha256": "ce4560ceaefda3d5db192f44d51193c7f1a48661f7e707edfe59eb4b36a31fc6",
        "facts": {
            "contextually_encoded": False,
            "control_status": 200,
            "probe_status": 200,
            "raw_html_context": True,
            "verification_reference": "0161fa83b2a941889c33bc210b4ab3bc",
        },
        "false_positive": False,
        "gate": "xss",
        "mode": "vulnerable",
        "outcome": "CONFIRMED",
        "scenario_id": "shop-promotion-preview-v1",
        "verifier_status": "CONFIRMED",
    },
    {
        "evidence_sha256": "ff8cff0bb52a5d7db1c5e132d3e4727308f02edc6b7af5d643e40676f23c8d4b",
        "facts": {
            "contextually_encoded": True,
            "control_status": 200,
            "probe_status": 200,
            "raw_html_context": False,
            "verification_reference": "e4c3b6c37a4a434a97c65cff5885206d",
        },
        "false_positive": False,
        "gate": "xss",
        "mode": "patched",
        "outcome": "PASS",
        "scenario_id": "shop-promotion-preview-v1",
        "verifier_status": "PASS",
    },
    {
        "evidence_sha256": "67d311414f63f752c87b3862f41e90eee4ae41c9dea9ee67ab62f7348e1a8bb1",
        "facts": {
            "control_result_count": 1,
            "control_status": 200,
            "probe_result_count": 3,
            "probe_status": 200,
            "verification_reference": "973f56cdb79e44beaa43b3afd344261f",
        },
        "false_positive": False,
        "gate": "sqli",
        "mode": "vulnerable",
        "outcome": "CONFIRMED",
        "scenario_id": "shop-catalog-query-v1",
        "verifier_status": "CONFIRMED",
    },
    {
        "evidence_sha256": "f85860f7cbe85cc5389d1bdfcabd134bf34c42b0ef772cc6caaabd863e4e4d41",
        "facts": {
            "control_result_count": 1,
            "control_status": 200,
            "probe_result_count": 0,
            "probe_status": 200,
            "verification_reference": "1db04f96479a4ed2adc9389567b760fe",
        },
        "false_positive": False,
        "gate": "sqli",
        "mode": "patched",
        "outcome": "PASS",
        "scenario_id": "shop-catalog-query-v1",
        "verifier_status": "PASS",
    },
    {
        "evidence_sha256": "053d8bcb47ad793853eeb2f82f26adc12eb5a5f2c38b0c5fec70d64d4e40c80b",
        "facts": {"links_complete": True, "recon_candidates": 2},
        "false_positive": False,
        "gate": "chain",
        "mode": "vulnerable",
        "outcome": "CONFIRMED",
        "scenario_id": "shop-promotion-preview-v1",
        "verifier_status": "CONFIRMED",
    },
    {
        "evidence_sha256": "f3dad8ac6e88d1d172b40667b369c45c2dabe196f87651a6230f3848565554b5",
        "facts": {"links_complete": True, "recon_candidates": 2},
        "false_positive": False,
        "gate": "chain",
        "mode": "patched",
        "outcome": "PASS",
        "scenario_id": "shop-promotion-preview-v1",
        "verifier_status": "PASS",
    },
]

_QUEUE_PAYLOAD: dict[str, object] = {
    "delegation_id": DELEGATION_ID,
    "from_agent": "RECON_AGENT",
    "to_agent": "INJECTION_AGENT",
    "capability_id": "aegis.http.injection",
    "target_ref": "range-shop",
    "route": "",
    "parameter": "",
    "rationale": "TEST_FIXTURE synthetic delegation: discovered HTTP service on range-shop.",
    "reference_only": False,
    "confirmed": False,
    "unconfirmed": True,
    "status": "QUEUED",
    "source_evidence_sha256": DELEGATION_EVIDENCE_SHA256,
    "enqueued_at": ENQUEUED_AT,
}


@dataclass(frozen=True)
class FixturePaths:
    """The paths the report builder consumes, plus the repo-relative queue path it cross-checks."""

    directory: Path
    verifier_results: Path
    acceptance: Path
    delegation_queue: Path


def _canonical_json(value: object) -> bytes:
    """Deterministic JSON bytes: sorted keys, 2-space indent, trailing newline."""

    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def _acceptance_document() -> dict[str, object]:
    return {
        "_fixture": FIXTURE_MARKER,
        "phase": "1.7-D-TEST-FIXTURE",
        "verdict": "PASS",
        "record": {
            "artifact_db_path": ARTIFACT_DB_PATH,
            "delegation_enqueue": {
                "address": QUEUE_ADDRESS,
                "confirmed": False,
                "unconfirmed": True,
                "source_evidence_sha256": DELEGATION_EVIDENCE_SHA256,
            },
        },
        "verdict_detail": {
            "passed": True,
            "checks": {
                "controller_owned_verdict": True,
                "live_provider_identity": "NOT_EVALUATED",
                "unknown_example": "UNKNOWN",
            },
        },
    }


def _write_queue(path: Path) -> None:
    """Write a deterministic single-row delegation queue matching the real Phase 1.7-D schema."""

    if path.exists():
        path.unlink()
    connection = sqlite3.connect(path)
    try:
        connection.execute(
            """
            CREATE TABLE agent_delegations (
                delegation_id TEXT PRIMARY KEY,
                to_agent TEXT NOT NULL,
                status TEXT NOT NULL,
                address TEXT NOT NULL UNIQUE,
                enqueued_at TEXT NOT NULL,
                source_evidence_sha256 TEXT NOT NULL,
                payload TEXT NOT NULL
            )
            """
        )
        connection.execute(
            "INSERT INTO agent_delegations "
            "(delegation_id, to_agent, status, address, enqueued_at, source_evidence_sha256, "
            "payload) VALUES (?,?,?,?,?,?,?)",
            (
                DELEGATION_ID,
                "INJECTION_AGENT",
                "QUEUED",
                QUEUE_ADDRESS,
                ENQUEUED_AT,
                DELEGATION_EVIDENCE_SHA256,
                json.dumps(_QUEUE_PAYLOAD, sort_keys=True),
            ),
        )
        connection.commit()
    finally:
        connection.close()


def write_fixture(dest: Path) -> FixturePaths:
    """Generate the TEST_FIXTURE evidence set under ``dest`` and return the consuming paths.

    The bytes are fully determined by the constants in this module (``acceptance.json`` records the
    fixed checked-in ``ARTIFACT_DB_PATH``), so regenerating anywhere reproduces the committed files.
    """

    dest.mkdir(parents=True, exist_ok=True)
    (dest / "TEST_FIXTURE").write_text(
        "Synthetic Phase 1.8 report inputs. Never live-provider evidence.\n", encoding="utf-8"
    )

    verifier_results = dest / "verifier-results.json"
    acceptance = dest / "acceptance.json"
    delegation_queue = dest / "delegation_queue.sqlite3"

    verifier_results.write_bytes(_canonical_json(_VERIFIER_RECORDS))
    _write_queue(delegation_queue)
    acceptance.write_bytes(_canonical_json(_acceptance_document()))

    checksums = []
    for item in (acceptance, delegation_queue, verifier_results):
        digest = hashlib.sha256(item.read_bytes()).hexdigest()
        checksums.append(f"{digest}  {item.name}")
    (dest / "SHA256SUMS").write_text("\n".join(sorted(checksums)) + "\n", encoding="utf-8")

    return FixturePaths(
        directory=dest,
        verifier_results=verifier_results,
        acceptance=acceptance,
        delegation_queue=delegation_queue,
    )


def default_fixture_dir(repo_root: Path) -> Path:
    """The checked-in fixture directory for a given repository root."""

    return repo_root / "tests" / "fixtures" / FIXTURE_DIRNAME


def ensure_fixture(repo_root: Path) -> FixturePaths:
    """Return the checked-in fixture paths, regenerating deterministically if any file is absent.

    In a normal checkout the files are committed and present, so this is a no-op that just resolves
    the paths; it self-heals only if the committed bytes were removed.
    """

    dest = default_fixture_dir(repo_root)
    expected = [
        dest / "verifier-results.json",
        dest / "acceptance.json",
        dest / "delegation_queue.sqlite3",
        dest / "SHA256SUMS",
    ]
    if all(path.is_file() for path in expected):
        return FixturePaths(
            directory=dest,
            verifier_results=expected[0],
            acceptance=expected[1],
            delegation_queue=expected[2],
        )
    return write_fixture(dest)
