"""WS3 — the checked-in TEST_FIXTURE evidence sets are deterministic and portable.

These tests guard the property that lets the offline suite run without a developer's private
``artifacts/`` directory: each fixture is generated by a deterministic generator, so regenerating it
reproduces the committed bytes exactly (byte-identity against a deterministic generator result), and
every fixture is unmistakably labelled ``TEST_FIXTURE`` so it can never be mistaken for live
evidence.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pytest
from phase_1_8_report_fixture import (
    FIXTURE_MARKER,
    default_fixture_dir,
)
from phase_1_8_report_fixture import (
    write_fixture as write_report_fixture,
)
from prior_evidence_fixture import write_fixture as write_prior_evidence_fixture


@pytest.fixture
def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def test_report_fixture_json_is_reproducible(repo_root: Path, tmp_path: Path) -> None:
    committed = default_fixture_dir(repo_root)
    regenerated = write_report_fixture(tmp_path / "regen")
    for name in ("verifier-results.json", "acceptance.json", "SHA256SUMS"):
        assert (committed / name).read_bytes() == (regenerated.directory / name).read_bytes(), (
            f"{name} is not reproduced byte-for-byte by the deterministic generator"
        )


def test_report_fixture_queue_content_is_reproducible(repo_root: Path, tmp_path: Path) -> None:
    committed = default_fixture_dir(repo_root) / "delegation_queue.sqlite3"
    regenerated = write_report_fixture(tmp_path / "regen").delegation_queue

    def _row(path: Path) -> tuple[object, ...]:
        connection = sqlite3.connect(f"file:{path.resolve()}?mode=ro", uri=True)
        try:
            return connection.execute(
                "SELECT delegation_id, to_agent, status, address, enqueued_at, "
                "source_evidence_sha256, payload FROM agent_delegations"
            ).fetchall()[0]
        finally:
            connection.close()

    assert _row(committed) == _row(regenerated)


def test_report_fixture_is_labelled_and_not_live(repo_root: Path) -> None:
    directory = default_fixture_dir(repo_root)
    assert (directory / "TEST_FIXTURE").is_file()
    acceptance = json.loads((directory / "acceptance.json").read_text(encoding="utf-8"))
    assert acceptance["_fixture"] == FIXTURE_MARKER
    # A live-provider identity is never asserted by a fixture.
    assert acceptance["verdict_detail"]["checks"]["live_provider_identity"] == "NOT_EVALUATED"


def test_prior_evidence_fixture_is_reproducible(repo_root: Path, tmp_path: Path) -> None:
    committed = repo_root / "tests" / "fixtures" / "prior_evidence"
    regenerated = write_prior_evidence_fixture(tmp_path / "regen").directory
    for name in ("evidence-alpha.txt", "evidence-beta.txt", "manifest.sha256"):
        assert (committed / name).read_bytes() == (regenerated / name).read_bytes()
    assert FIXTURE_MARKER in (committed / "evidence-alpha.txt").read_text(encoding="utf-8")
